development:
  adapter: postgresql
  encoding: utf8
  database: web_church_app
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: church_app_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: web_church_app
  pool: 5
  username:
  password:
