
alert 'helolo everyone'
alert 'djkajdkajfkdjkafjdkjafkdjkjdfkjakfjdkjj'
# $ ->
#   $('#like_and_unlike').on  "ajax:success", (ev) ->
#     $('#like_and_unlike').load(document.URL +  ' #like_and_unlike');



    # $ ->
    #   $('.comments').load(document.URL +  ' .comments');
    #   $('.simple_form.new_comment').on  "ajax:success", (event) ->



$(document).ready ->
  # with minimal configuration and default setting
  slides = []

  shown = (slide) ->
    console.log 'Slide shown: ', slide.find('img').attr('src')
    return

  i = 0
  while i < 5
    slides.push src: 'https://unsplash.it/' + 1366 + i + '/' + 768 + i
    i++
  $('.jR3DCarouselGalleryDefault').jR3DCarousel slides: slides
  # Or with options
  $('.jR3DCarouselGalleryCustom').jR3DCarousel
    width: 470
    height: 272
    slideLayout: 'fill'
    animation: 'slide3D'
    animationCurve: 'ease'
    animationDuration: 700
    animationInterval: 1000
    slideClass: 'jR3DCarouselCustomSlide'
    autoplay: false
    onSlideShow: shown
    navigation: 'circles'
    perspective: 1200
  return

# ---
# generated by js2coffee 2.2.0
